### ISSUE TITLE
Valkey-cluster cannot be accessible  outside of Kubernets 

### ISSUE THREAD

**Issue by sujitkagarwal** [hyperspike/valkey-operator#111]
Valkey-cluster cannot be accessible  outside of Kubernets , if we change the service Type as loadBalancer.

**Comment by dmolik** [comment]
this is actually an interesting problem. Valkey Clustering will actually forward requests from one node to the other, if the key is not in the node local shard. So basically with a loadbalancer and 3 shards you have a 1 in 3 chance of a cache hit. I think this would work with 3 loadbalancers, but that sounds pretty expensive. I'll check to see if there is a cluster proxy.

**Comment by dmolik** [comment]
I forgot, it's not possible for Services Ports to have independent selectors. I can implement this with multiple loadbalancers, and alternatively the redis-cluster-proxy.

**Comment by dmolik** [comment]
I'm going to consider this more or less complete and close in a week or so
