### ISSUE TITLE
Any way to pass custom labels down from the valkey CRD -> statefulset -> pods

### ISSUE THREAD

**Issue by iggy** [hyperspike/valkey-operator#139]
We have the need to be able to set custom labels on k8s objects for an admission controller that we use. I looked through the docs and the code a bit to see if I could figure out how to do that. Is there support for this?

**Comment by dmolik** [comment]
Sorry about that, I thought I had updated the labels func to push custom labels down from the crd instantiation. I'll get a draft PR ready in the business day or so I'll link it here when I push it up.

**Comment by dmolik** [comment]
let me know if this criteria is good enough: https://github.com/hyperspike/valkey-operator/blob/3182461d24a367f69de814a5a9be5006b32434dc/internal/controller/valkey_controller_utils_test.go#L26-L47
