### ISSUE TITLE
how to set the password

### ISSUE THREAD

**Issue by tobstone** [hyperspike/valkey-operator#148]
I dont understand how to set the password or no password with the CRD, is this implented yet?  thx for your work!

**Comment by dmolik** [comment]
Currently, the password is auto generated and stored in a kubernetes secret of the same name as the custom resource instance. Under the key name of password. I can make changes to account for setting the password in the next couple of days. I'll link the PR here when it's up.

**Comment by travisghansen** [comment]
Is it possible to allow anonymous auth?

**Comment by dmolik** [comment]
@travisghansen not at the moment, the default behavior is to generate  a password and drop it into a secret of the same name as the Valkey Cluster, I'll create an issue to support it though. That being said I feel obligated to say, I don't recommend anonymous auth.

**Comment by travisghansen** [comment]
Thanks! I'm dealing with tooling (operators, apps, etc) which simply don't support auth unfortunately.

**Comment by dmolik** [comment]
Gotcha, I'll get you unblocked then.
