### ISSUE TITLE
Sign image and helm chart 

### ISSUE THREAD

**Issue by dmolik** [hyperspike/valkey-operator#53]

**Comment by koalalorenzo** [comment]
Hello! Where can we find the Helm Chart? :)

**Comment by dmolik** [comment]
hi @koalalorenzo
yes, the chart can be found here: https://github.com/hyperspike/valkey-operator/pkgs/container/valkey-operator-chart

and can be inspected with this command:
```sh
helm pull --untar oci://ghcr.io/hyperspike/valkey-operator-chart --version v0.0.27
```

or just straight installed with:
```sh
helm pull valkey-operator oci://ghcr.io/hyperspike/valkey-operator-chart --version v0.0.27
```
