### ISSUE TITLE
Can't install v0.0.28 via Helm

### ISSUE THREAD

**Issue by ahoka** [hyperspike/valkey-operator#67]
Pulled: ghcr.io/hyperspike/valkey-operator-chart:v0.0.28
Digest: sha256:6d1fd9e103aa78cf66e2835936f4ff39ceedee8af3cbac5aff19196e602a76fc
Error: INSTALLATION FAILED: 1 error occurred:
	* Deployment.apps "valkey-operator-chart-controller-manager" is invalid: [spec.template.spec.containers[0].env[0].valueFrom.fieldRef.fieldPath: Invalid value: "metadata.labels[app.kubernetes.io/name]": error converting fieldPath: field label not supported: metadata.labels[app.kubernetes.io/name], spec.template.spec.containers[0].env[1].valueFrom.fieldRef.fieldPath: Invalid value: "metadata.labels[app.kubernetes.io/instance]": error converting fieldPath: field label not supported: metadata.labels[app.kubernetes.io/instance]]

Env:

colima version 0.7.5
git commit: 1588c066b9ab9dae8205ef265929c7eb43dca473

runtime: docker
arch: aarch64
client: v27.2.1
server: v27.1.1

kubernetes
Client Version: v1.23.0
Server Version: v1.30.2+k3s1

**Comment by dmolik** [comment]
helmify dropped single quotes from the metadata target in envs, I've got an issue going: https://github.com/arttor/helmify/issues/151 but I put a temporary fix in-place in the meantime:

please try the latest release ( https://github.com/hyperspike/valkey-operator/releases/tag/v0.0.30 )

**Comment by ahoka** [comment]
Will, do thanks!
